
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point x_even[8] x_even[8] -type PI PI
add mapped point x_even[7] x_even[7] -type PI PI
add mapped point x_even[6] x_even[6] -type PI PI
add mapped point x_even[5] x_even[5] -type PI PI
add mapped point x_even[4] x_even[4] -type PI PI
add mapped point x_even[3] x_even[3] -type PI PI
add mapped point x_even[2] x_even[2] -type PI PI
add mapped point x_even[1] x_even[1] -type PI PI
add mapped point x_even[0] x_even[0] -type PI PI
add mapped point x_odd[8] x_odd[8] -type PI PI
add mapped point x_odd[7] x_odd[7] -type PI PI
add mapped point x_odd[6] x_odd[6] -type PI PI
add mapped point x_odd[5] x_odd[5] -type PI PI
add mapped point x_odd[4] x_odd[4] -type PI PI
add mapped point x_odd[3] x_odd[3] -type PI PI
add mapped point x_odd[2] x_odd[2] -type PI PI
add mapped point x_odd[1] x_odd[1] -type PI PI
add mapped point x_odd[0] x_odd[0] -type PI PI
add mapped point theta[8] theta[8] -type PI PI
add mapped point theta[7] theta[7] -type PI PI
add mapped point theta[6] theta[6] -type PI PI
add mapped point theta[5] theta[5] -type PI PI
add mapped point theta[4] theta[4] -type PI PI
add mapped point theta[3] theta[3] -type PI PI
add mapped point theta[2] theta[2] -type PI PI
add mapped point theta[1] theta[1] -type PI PI
add mapped point theta[0] theta[0] -type PI PI

//output ports
add mapped point y_even[8] y_even[8] -type PO PO
add mapped point y_even[7] y_even[7] -type PO PO
add mapped point y_even[6] y_even[6] -type PO PO
add mapped point y_even[5] y_even[5] -type PO PO
add mapped point y_even[4] y_even[4] -type PO PO
add mapped point y_even[3] y_even[3] -type PO PO
add mapped point y_even[2] y_even[2] -type PO PO
add mapped point y_even[1] y_even[1] -type PO PO
add mapped point y_even[0] y_even[0] -type PO PO
add mapped point y_odd[8] y_odd[8] -type PO PO
add mapped point y_odd[7] y_odd[7] -type PO PO
add mapped point y_odd[6] y_odd[6] -type PO PO
add mapped point y_odd[5] y_odd[5] -type PO PO
add mapped point y_odd[4] y_odd[4] -type PO PO
add mapped point y_odd[3] y_odd[3] -type PO PO
add mapped point y_odd[2] y_odd[2] -type PO PO
add mapped point y_odd[1] y_odd[1] -type PO PO
add mapped point y_odd[0] y_odd[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point rot/x_reg[1][0]/q rot_x_reg_reg[1][0]/Q  -type DFF DFF
add mapped point rot/x_reg[1][1]/q rot_x_reg_reg[1][1]/Q  -type DFF DFF
add mapped point rot/x_reg[1][2]/q rot_x_reg_reg[1][2]/Q  -type DFF DFF
add mapped point rot/x_reg[1][3]/q rot_x_reg_reg[1][3]/Q  -type DFF DFF
add mapped point rot/x_reg[1][4]/q rot_x_reg_reg[1][4]/Q  -type DFF DFF
add mapped point rot/x_reg[1][5]/q rot_x_reg_reg[1][5]/Q  -type DFF DFF
add mapped point rot/x_reg[1][6]/q rot_x_reg_reg[1][6]/Q  -type DFF DFF
add mapped point rot/x_reg[1][7]/q rot_x_reg_reg[1][7]/Q  -type DFF DFF
add mapped point rot/x_reg[1][8]/q rot_x_reg_reg[1][8]/Q  -type DFF DFF
add mapped point rot/x_reg[2][0]/q rot_x_reg_reg[2][0]/Q  -type DFF DFF
add mapped point rot/x_reg[2][1]/q rot_x_reg_reg[2][1]/Q  -type DFF DFF
add mapped point rot/x_reg[2][2]/q rot_x_reg_reg[2][2]/Q  -type DFF DFF
add mapped point rot/x_reg[2][3]/q rot_x_reg_reg[2][3]/Q  -type DFF DFF
add mapped point rot/x_reg[2][4]/q rot_x_reg_reg[2][4]/Q  -type DFF DFF
add mapped point rot/x_reg[2][5]/q rot_x_reg_reg[2][5]/Q  -type DFF DFF
add mapped point rot/x_reg[2][6]/q rot_x_reg_reg[2][6]/Q  -type DFF DFF
add mapped point rot/x_reg[2][7]/q rot_x_reg_reg[2][7]/Q  -type DFF DFF
add mapped point rot/x_reg[2][8]/q rot_x_reg_reg[2][8]/Q  -type DFF DFF
add mapped point rot/x_reg[3][0]/q rot_x_reg_reg[3][0]/Q  -type DFF DFF
add mapped point rot/x_reg[3][1]/q rot_x_reg_reg[3][1]/Q  -type DFF DFF
add mapped point rot/x_reg[3][2]/q rot_x_reg_reg[3][2]/Q  -type DFF DFF
add mapped point rot/x_reg[3][3]/q rot_x_reg_reg[3][3]/Q  -type DFF DFF
add mapped point rot/x_reg[3][4]/q rot_x_reg_reg[3][4]/Q  -type DFF DFF
add mapped point rot/x_reg[3][5]/q rot_x_reg_reg[3][5]/Q  -type DFF DFF
add mapped point rot/x_reg[3][6]/q rot_x_reg_reg[3][6]/Q  -type DFF DFF
add mapped point rot/x_reg[3][7]/q rot_x_reg_reg[3][7]/Q  -type DFF DFF
add mapped point rot/x_reg[3][8]/q rot_x_reg_reg[3][8]/Q  -type DFF DFF
add mapped point rot/x_reg[4][0]/q rot_x_reg_reg[4][0]/Q  -type DFF DFF
add mapped point rot/x_reg[4][1]/q rot_x_reg_reg[4][1]/Q  -type DFF DFF
add mapped point rot/x_reg[4][2]/q rot_x_reg_reg[4][2]/Q  -type DFF DFF
add mapped point rot/x_reg[4][3]/q rot_x_reg_reg[4][3]/Q  -type DFF DFF
add mapped point rot/x_reg[4][4]/q rot_x_reg_reg[4][4]/Q  -type DFF DFF
add mapped point rot/x_reg[4][5]/q rot_x_reg_reg[4][5]/Q  -type DFF DFF
add mapped point rot/x_reg[4][6]/q rot_x_reg_reg[4][6]/Q  -type DFF DFF
add mapped point rot/x_reg[4][7]/q rot_x_reg_reg[4][7]/Q  -type DFF DFF
add mapped point rot/x_reg[4][8]/q rot_x_reg_reg[4][8]/Q  -type DFF DFF
add mapped point rot/x_reg[5][0]/q rot_x_reg_reg[5][0]/Q  -type DFF DFF
add mapped point rot/x_reg[5][1]/q rot_x_reg_reg[5][1]/Q  -type DFF DFF
add mapped point rot/x_reg[5][2]/q rot_x_reg_reg[5][2]/Q  -type DFF DFF
add mapped point rot/x_reg[5][3]/q rot_x_reg_reg[5][3]/Q  -type DFF DFF
add mapped point rot/x_reg[5][4]/q rot_x_reg_reg[5][4]/Q  -type DFF DFF
add mapped point rot/x_reg[5][6]/q rot_x_reg_reg[5][6]/Q  -type DFF DFF
add mapped point rot/x_reg[5][7]/q rot_x_reg_reg[5][7]/Q  -type DFF DFF
add mapped point rot/x_reg[5][8]/q rot_x_reg_reg[5][8]/Q  -type DFF DFF
add mapped point rot/x_reg[6][0]/q rot_x_reg_reg[6][0]/Q  -type DFF DFF
add mapped point rot/x_reg[6][1]/q rot_x_reg_reg[6][1]/Q  -type DFF DFF
add mapped point rot/x_reg[6][2]/q rot_x_reg_reg[6][2]/Q  -type DFF DFF
add mapped point rot/x_reg[6][3]/q rot_x_reg_reg[6][3]/Q  -type DFF DFF
add mapped point rot/x_reg[6][4]/q rot_x_reg_reg[6][4]/Q  -type DFF DFF
add mapped point rot/x_reg[6][5]/q rot_x_reg_reg[6][5]/Q  -type DFF DFF
add mapped point rot/x_reg[6][6]/q rot_x_reg_reg[6][6]/Q  -type DFF DFF
add mapped point rot/x_reg[6][7]/q rot_x_reg_reg[6][7]/Q  -type DFF DFF
add mapped point rot/x_reg[6][8]/q rot_x_reg_reg[6][8]/Q  -type DFF DFF
add mapped point rot/x_reg[7][0]/q rot_x_reg_reg[7][0]/Q  -type DFF DFF
add mapped point rot/x_reg[7][1]/q rot_x_reg_reg[7][1]/Q  -type DFF DFF
add mapped point rot/x_reg[7][2]/q rot_x_reg_reg[7][2]/Q  -type DFF DFF
add mapped point rot/x_reg[7][3]/q rot_x_reg_reg[7][3]/Q  -type DFF DFF
add mapped point rot/x_reg[7][4]/q rot_x_reg_reg[7][4]/Q  -type DFF DFF
add mapped point rot/x_reg[7][5]/q rot_x_reg_reg[7][5]/Q  -type DFF DFF
add mapped point rot/x_reg[7][6]/q rot_x_reg_reg[7][6]/Q  -type DFF DFF
add mapped point rot/x_reg[7][7]/q rot_x_reg_reg[7][7]/Q  -type DFF DFF
add mapped point rot/x_reg[7][8]/q rot_x_reg_reg[7][8]/Q  -type DFF DFF
add mapped point rot/x_reg[8][0]/q rot_x_reg_reg[8][0]/Q  -type DFF DFF
add mapped point rot/x_reg[8][1]/q rot_x_reg_reg[8][1]/Q  -type DFF DFF
add mapped point rot/x_reg[8][2]/q rot_x_reg_reg[8][2]/Q  -type DFF DFF
add mapped point rot/x_reg[8][3]/q rot_x_reg_reg[8][3]/Q  -type DFF DFF
add mapped point rot/x_reg[8][4]/q rot_x_reg_reg[8][4]/Q  -type DFF DFF
add mapped point rot/x_reg[8][5]/q rot_x_reg_reg[8][5]/Q  -type DFF DFF
add mapped point rot/x_reg[8][6]/q rot_x_reg_reg[8][6]/Q  -type DFF DFF
add mapped point rot/x_reg[8][7]/q rot_x_reg_reg[8][7]/Q  -type DFF DFF
add mapped point rot/x_reg[8][8]/q rot_x_reg_reg[8][8]/Q  -type DFF DFF
add mapped point rot/x_reg[9][0]/q rot_x_reg_reg[9][0]/Q  -type DFF DFF
add mapped point rot/x_reg[9][1]/q rot_x_reg_reg[9][1]/Q  -type DFF DFF
add mapped point rot/x_reg[9][2]/q rot_x_reg_reg[9][2]/Q  -type DFF DFF
add mapped point rot/x_reg[9][3]/q rot_x_reg_reg[9][3]/Q  -type DFF DFF
add mapped point rot/x_reg[9][4]/q rot_x_reg_reg[9][4]/Q  -type DFF DFF
add mapped point rot/x_reg[9][5]/q rot_x_reg_reg[9][5]/Q  -type DFF DFF
add mapped point rot/x_reg[9][6]/q rot_x_reg_reg[9][6]/Q  -type DFF DFF
add mapped point rot/x_reg[9][7]/q rot_x_reg_reg[9][7]/Q  -type DFF DFF
add mapped point rot/x_reg[9][8]/q rot_x_reg_reg[9][8]/Q  -type DFF DFF
add mapped point rot/x_reg[10][0]/q rot_x_reg_reg[10][0]/Q  -type DFF DFF
add mapped point rot/x_reg[10][1]/q rot_x_reg_reg[10][1]/Q  -type DFF DFF
add mapped point rot/x_reg[10][2]/q rot_x_reg_reg[10][2]/Q  -type DFF DFF
add mapped point rot/x_reg[10][3]/q rot_x_reg_reg[10][3]/Q  -type DFF DFF
add mapped point rot/x_reg[10][4]/q rot_x_reg_reg[10][4]/Q  -type DFF DFF
add mapped point rot/x_reg[10][5]/q rot_x_reg_reg[10][5]/Q  -type DFF DFF
add mapped point rot/x_reg[10][6]/q rot_x_reg_reg[10][6]/Q  -type DFF DFF
add mapped point rot/x_reg[10][7]/q rot_x_reg_reg[10][7]/Q  -type DFF DFF
add mapped point rot/x_reg[10][8]/q rot_x_reg_reg[10][8]/Q  -type DFF DFF
add mapped point rot/y_reg[1][1]/q rot_y_reg_reg[1][1]/Q  -type DFF DFF
add mapped point rot/y_reg[1][2]/q rot_y_reg_reg[1][2]/Q  -type DFF DFF
add mapped point rot/y_reg[1][3]/q rot_y_reg_reg[1][3]/Q  -type DFF DFF
add mapped point rot/y_reg[1][4]/q rot_y_reg_reg[1][4]/Q  -type DFF DFF
add mapped point rot/y_reg[1][5]/q rot_y_reg_reg[1][5]/Q  -type DFF DFF
add mapped point rot/y_reg[1][6]/q rot_y_reg_reg[1][6]/Q  -type DFF DFF
add mapped point rot/y_reg[1][7]/q rot_y_reg_reg[1][7]/Q  -type DFF DFF
add mapped point rot/y_reg[1][8]/q rot_y_reg_reg[1][8]/Q  -type DFF DFF
add mapped point rot/y_reg[2][0]/q rot_y_reg_reg[2][0]/Q  -type DFF DFF
add mapped point rot/y_reg[2][1]/q rot_y_reg_reg[2][1]/Q  -type DFF DFF
add mapped point rot/y_reg[2][2]/q rot_y_reg_reg[2][2]/Q  -type DFF DFF
add mapped point rot/y_reg[2][3]/q rot_y_reg_reg[2][3]/Q  -type DFF DFF
add mapped point rot/y_reg[2][4]/q rot_y_reg_reg[2][4]/Q  -type DFF DFF
add mapped point rot/y_reg[2][5]/q rot_y_reg_reg[2][5]/Q  -type DFF DFF
add mapped point rot/y_reg[2][6]/q rot_y_reg_reg[2][6]/Q  -type DFF DFF
add mapped point rot/y_reg[2][7]/q rot_y_reg_reg[2][7]/Q  -type DFF DFF
add mapped point rot/y_reg[2][8]/q rot_y_reg_reg[2][8]/Q  -type DFF DFF
add mapped point rot/y_reg[3][0]/q rot_y_reg_reg[3][0]/Q  -type DFF DFF
add mapped point rot/y_reg[3][1]/q rot_y_reg_reg[3][1]/Q  -type DFF DFF
add mapped point rot/y_reg[3][2]/q rot_y_reg_reg[3][2]/Q  -type DFF DFF
add mapped point rot/y_reg[3][3]/q rot_y_reg_reg[3][3]/Q  -type DFF DFF
add mapped point rot/y_reg[3][4]/q rot_y_reg_reg[3][4]/Q  -type DFF DFF
add mapped point rot/y_reg[3][5]/q rot_y_reg_reg[3][5]/Q  -type DFF DFF
add mapped point rot/y_reg[3][6]/q rot_y_reg_reg[3][6]/Q  -type DFF DFF
add mapped point rot/y_reg[3][7]/q rot_y_reg_reg[3][7]/Q  -type DFF DFF
add mapped point rot/y_reg[3][8]/q rot_y_reg_reg[3][8]/Q  -type DFF DFF
add mapped point rot/y_reg[4][0]/q rot_y_reg_reg[4][0]/Q  -type DFF DFF
add mapped point rot/y_reg[4][1]/q rot_y_reg_reg[4][1]/Q  -type DFF DFF
add mapped point rot/y_reg[4][2]/q rot_y_reg_reg[4][2]/Q  -type DFF DFF
add mapped point rot/y_reg[4][3]/q rot_y_reg_reg[4][3]/Q  -type DFF DFF
add mapped point rot/y_reg[4][4]/q rot_y_reg_reg[4][4]/Q  -type DFF DFF
add mapped point rot/y_reg[4][5]/q rot_y_reg_reg[4][5]/Q  -type DFF DFF
add mapped point rot/y_reg[4][6]/q rot_y_reg_reg[4][6]/Q  -type DFF DFF
add mapped point rot/y_reg[4][7]/q rot_y_reg_reg[4][7]/Q  -type DFF DFF
add mapped point rot/y_reg[4][8]/q rot_y_reg_reg[4][8]/Q  -type DFF DFF
add mapped point rot/y_reg[5][0]/q rot_y_reg_reg[5][0]/Q  -type DFF DFF
add mapped point rot/y_reg[5][1]/q rot_y_reg_reg[5][1]/Q  -type DFF DFF
add mapped point rot/y_reg[5][2]/q rot_y_reg_reg[5][2]/Q  -type DFF DFF
add mapped point rot/y_reg[5][3]/q rot_y_reg_reg[5][3]/Q  -type DFF DFF
add mapped point rot/y_reg[5][4]/q rot_y_reg_reg[5][4]/Q  -type DFF DFF
add mapped point rot/y_reg[5][5]/q rot_y_reg_reg[5][5]/Q  -type DFF DFF
add mapped point rot/y_reg[5][6]/q rot_y_reg_reg[5][6]/Q  -type DFF DFF
add mapped point rot/y_reg[5][7]/q rot_y_reg_reg[5][7]/Q  -type DFF DFF
add mapped point rot/y_reg[5][8]/q rot_y_reg_reg[5][8]/Q  -type DFF DFF
add mapped point rot/y_reg[6][0]/q rot_y_reg_reg[6][0]/Q  -type DFF DFF
add mapped point rot/y_reg[6][1]/q rot_y_reg_reg[6][1]/Q  -type DFF DFF
add mapped point rot/y_reg[6][2]/q rot_y_reg_reg[6][2]/Q  -type DFF DFF
add mapped point rot/y_reg[6][3]/q rot_y_reg_reg[6][3]/Q  -type DFF DFF
add mapped point rot/y_reg[6][4]/q rot_y_reg_reg[6][4]/Q  -type DFF DFF
add mapped point rot/y_reg[6][5]/q rot_y_reg_reg[6][5]/Q  -type DFF DFF
add mapped point rot/y_reg[6][6]/q rot_y_reg_reg[6][6]/Q  -type DFF DFF
add mapped point rot/y_reg[6][7]/q rot_y_reg_reg[6][7]/Q  -type DFF DFF
add mapped point rot/y_reg[6][8]/q rot_y_reg_reg[6][8]/Q  -type DFF DFF
add mapped point rot/y_reg[7][0]/q rot_y_reg_reg[7][0]/Q  -type DFF DFF
add mapped point rot/y_reg[7][1]/q rot_y_reg_reg[7][1]/Q  -type DFF DFF
add mapped point rot/y_reg[7][2]/q rot_y_reg_reg[7][2]/Q  -type DFF DFF
add mapped point rot/y_reg[7][3]/q rot_y_reg_reg[7][3]/Q  -type DFF DFF
add mapped point rot/y_reg[7][4]/q rot_y_reg_reg[7][4]/Q  -type DFF DFF
add mapped point rot/y_reg[7][5]/q rot_y_reg_reg[7][5]/Q  -type DFF DFF
add mapped point rot/y_reg[7][6]/q rot_y_reg_reg[7][6]/Q  -type DFF DFF
add mapped point rot/y_reg[7][7]/q rot_y_reg_reg[7][7]/Q  -type DFF DFF
add mapped point rot/y_reg[7][8]/q rot_y_reg_reg[7][8]/Q  -type DFF DFF
add mapped point rot/y_reg[8][0]/q rot_y_reg_reg[8][0]/Q  -type DFF DFF
add mapped point rot/y_reg[8][0]/q rot_y_reg_reg[8][0]/QN  -type DFF DFF
add mapped point rot/y_reg[8][1]/q rot_y_reg_reg[8][1]/Q  -type DFF DFF
add mapped point rot/y_reg[8][2]/q rot_y_reg_reg[8][2]/Q  -type DFF DFF
add mapped point rot/y_reg[8][3]/q rot_y_reg_reg[8][3]/Q  -type DFF DFF
add mapped point rot/y_reg[8][4]/q rot_y_reg_reg[8][4]/Q  -type DFF DFF
add mapped point rot/y_reg[8][5]/q rot_y_reg_reg[8][5]/Q  -type DFF DFF
add mapped point rot/y_reg[8][6]/q rot_y_reg_reg[8][6]/Q  -type DFF DFF
add mapped point rot/y_reg[8][7]/q rot_y_reg_reg[8][7]/Q  -type DFF DFF
add mapped point rot/y_reg[8][8]/q rot_y_reg_reg[8][8]/Q  -type DFF DFF
add mapped point rot/y_reg[9][0]/q rot_y_reg_reg[9][0]/Q  -type DFF DFF
add mapped point rot/y_reg[9][1]/q rot_y_reg_reg[9][1]/Q  -type DFF DFF
add mapped point rot/y_reg[9][2]/q rot_y_reg_reg[9][2]/Q  -type DFF DFF
add mapped point rot/y_reg[9][3]/q rot_y_reg_reg[9][3]/Q  -type DFF DFF
add mapped point rot/y_reg[9][4]/q rot_y_reg_reg[9][4]/Q  -type DFF DFF
add mapped point rot/y_reg[9][5]/q rot_y_reg_reg[9][5]/Q  -type DFF DFF
add mapped point rot/y_reg[9][6]/q rot_y_reg_reg[9][6]/Q  -type DFF DFF
add mapped point rot/y_reg[9][7]/q rot_y_reg_reg[9][7]/Q  -type DFF DFF
add mapped point rot/y_reg[9][8]/q rot_y_reg_reg[9][8]/Q  -type DFF DFF
add mapped point rot/y_reg[10][0]/q rot_y_reg_reg[10][0]/Q  -type DFF DFF
add mapped point rot/y_reg[10][1]/q rot_y_reg_reg[10][1]/Q  -type DFF DFF
add mapped point rot/y_reg[10][2]/q rot_y_reg_reg[10][2]/Q  -type DFF DFF
add mapped point rot/y_reg[10][3]/q rot_y_reg_reg[10][3]/Q  -type DFF DFF
add mapped point rot/y_reg[10][4]/q rot_y_reg_reg[10][4]/Q  -type DFF DFF
add mapped point rot/y_reg[10][5]/q rot_y_reg_reg[10][5]/Q  -type DFF DFF
add mapped point rot/y_reg[10][6]/q rot_y_reg_reg[10][6]/Q  -type DFF DFF
add mapped point rot/y_reg[10][7]/q rot_y_reg_reg[10][7]/Q  -type DFF DFF
add mapped point rot/y_reg[10][8]/q rot_y_reg_reg[10][8]/Q  -type DFF DFF
add mapped point rot/z_reg[1][0]/q rot_z_reg_reg[1][0]/Q  -type DFF DFF
add mapped point rot/z_reg[1][1]/q rot_z_reg_reg[1][1]/Q  -type DFF DFF
add mapped point rot/z_reg[1][2]/q rot_z_reg_reg[1][2]/Q  -type DFF DFF
add mapped point rot/z_reg[1][3]/q rot_z_reg_reg[1][3]/Q  -type DFF DFF
add mapped point rot/z_reg[1][4]/q rot_z_reg_reg[1][4]/Q  -type DFF DFF
add mapped point rot/z_reg[1][5]/q rot_z_reg_reg[1][5]/Q  -type DFF DFF
add mapped point rot/z_reg[1][6]/q rot_z_reg_reg[1][6]/Q  -type DFF DFF
add mapped point rot/z_reg[1][7]/q rot_z_reg_reg[1][7]/Q  -type DFF DFF
add mapped point rot/z_reg[2][0]/q rot_z_reg_reg[2][0]/Q  -type DFF DFF
add mapped point rot/z_reg[2][1]/q rot_z_reg_reg[2][1]/Q  -type DFF DFF
add mapped point rot/z_reg[2][2]/q rot_z_reg_reg[2][2]/Q  -type DFF DFF
add mapped point rot/z_reg[2][3]/q rot_z_reg_reg[2][3]/Q  -type DFF DFF
add mapped point rot/z_reg[2][4]/q rot_z_reg_reg[2][4]/Q  -type DFF DFF
add mapped point rot/z_reg[2][5]/q rot_z_reg_reg[2][5]/Q  -type DFF DFF
add mapped point rot/z_reg[2][6]/q rot_z_reg_reg[2][6]/Q  -type DFF DFF
add mapped point rot/z_reg[2][7]/q rot_z_reg_reg[2][7]/Q  -type DFF DFF
add mapped point rot/z_reg[2][8]/q rot_z_reg_reg[2][8]/Q  -type DFF DFF
add mapped point rot/z_reg[2][8]/q rot_z_reg_reg[2][8]/QN  -type DFF DFF
add mapped point rot/z_reg[3][0]/q rot_z_reg_reg[3][0]/Q  -type DFF DFF
add mapped point rot/z_reg[3][1]/q rot_z_reg_reg[3][1]/Q  -type DFF DFF
add mapped point rot/z_reg[3][2]/q rot_z_reg_reg[3][2]/Q  -type DFF DFF
add mapped point rot/z_reg[3][3]/q rot_z_reg_reg[3][3]/Q  -type DFF DFF
add mapped point rot/z_reg[3][4]/q rot_z_reg_reg[3][4]/Q  -type DFF DFF
add mapped point rot/z_reg[3][5]/q rot_z_reg_reg[3][5]/Q  -type DFF DFF
add mapped point rot/z_reg[3][6]/q rot_z_reg_reg[3][6]/Q  -type DFF DFF
add mapped point rot/z_reg[3][7]/q rot_z_reg_reg[3][7]/Q  -type DFF DFF
add mapped point rot/z_reg[3][8]/q rot_z_reg_reg[3][8]/Q  -type DFF DFF
add mapped point rot/z_reg[3][8]/q rot_z_reg_reg[3][8]/QN  -type DFF DFF
add mapped point rot/z_reg[4][0]/q rot_z_reg_reg[4][0]/Q  -type DFF DFF
add mapped point rot/z_reg[4][1]/q rot_z_reg_reg[4][1]/Q  -type DFF DFF
add mapped point rot/z_reg[4][2]/q rot_z_reg_reg[4][2]/Q  -type DFF DFF
add mapped point rot/z_reg[4][3]/q rot_z_reg_reg[4][3]/Q  -type DFF DFF
add mapped point rot/z_reg[4][4]/q rot_z_reg_reg[4][4]/Q  -type DFF DFF
add mapped point rot/z_reg[4][5]/q rot_z_reg_reg[4][5]/Q  -type DFF DFF
add mapped point rot/z_reg[4][6]/q rot_z_reg_reg[4][6]/Q  -type DFF DFF
add mapped point rot/z_reg[4][7]/q rot_z_reg_reg[4][7]/Q  -type DFF DFF
add mapped point rot/z_reg[4][8]/q rot_z_reg_reg[4][8]/Q  -type DFF DFF
add mapped point rot/z_reg[4][8]/q rot_z_reg_reg[4][8]/QN  -type DFF DFF
add mapped point rot/z_reg[5][0]/q rot_z_reg_reg[5][0]/Q  -type DFF DFF
add mapped point rot/z_reg[5][1]/q rot_z_reg_reg[5][1]/Q  -type DFF DFF
add mapped point rot/z_reg[5][2]/q rot_z_reg_reg[5][2]/Q  -type DFF DFF
add mapped point rot/z_reg[5][3]/q rot_z_reg_reg[5][3]/Q  -type DFF DFF
add mapped point rot/z_reg[5][4]/q rot_z_reg_reg[5][4]/Q  -type DFF DFF
add mapped point rot/z_reg[5][4]/q rot_z_reg_reg[5][4]/QN  -type DFF DFF
add mapped point rot/z_reg[5][5]/q rot_z_reg_reg[5][5]/Q  -type DFF DFF
add mapped point rot/z_reg[5][6]/q rot_z_reg_reg[5][6]/Q  -type DFF DFF
add mapped point rot/z_reg[5][7]/q rot_z_reg_reg[5][7]/Q  -type DFF DFF
add mapped point rot/z_reg[6][0]/q rot_z_reg_reg[6][0]/Q  -type DFF DFF
add mapped point rot/z_reg[6][1]/q rot_z_reg_reg[6][1]/Q  -type DFF DFF
add mapped point rot/z_reg[6][2]/q rot_z_reg_reg[6][2]/Q  -type DFF DFF
add mapped point rot/z_reg[6][3]/q rot_z_reg_reg[6][3]/Q  -type DFF DFF
add mapped point rot/z_reg[6][4]/q rot_z_reg_reg[6][4]/Q  -type DFF DFF
add mapped point rot/z_reg[6][5]/q rot_z_reg_reg[6][5]/Q  -type DFF DFF
add mapped point rot/z_reg[6][6]/q rot_z_reg_reg[6][6]/Q  -type DFF DFF
add mapped point rot/z_reg[6][7]/q rot_z_reg_reg[6][7]/Q  -type DFF DFF
add mapped point rot/z_reg[6][8]/q rot_z_reg_reg[6][8]/Q  -type DFF DFF
add mapped point rot/z_reg[8][8]/q rot_z_reg_reg[8][8]/Q  -type DFF DFF
add mapped point rot/z_reg[8][8]/q rot_z_reg_reg[8][8]/QN  -type DFF DFF
add mapped point rot/x_reg[5][5]/q rot_x_reg_reg[5][5]/Q  -type DFF DFF
add mapped point rot/x_reg[5][5]/q rot_x_reg_reg[5][5]/QN  -type DFF DFF
add mapped point rot/z_reg[1][8]/q rot_z_reg_reg[1][8]/Q  -type DFF DFF
add mapped point rot/z_reg[1][8]/q rot_z_reg_reg[1][8]/QN  -type DFF DFF
add mapped point rot/z_reg[5][8]/q rot_z_reg_reg[5][8]/Q  -type DFF DFF
add mapped point rot/z_reg[5][8]/q rot_z_reg_reg[5][8]/QN  -type DFF DFF
add mapped point rot/z_reg[7][8]/q rot_z_reg_reg[7][8]/Q  -type DFF DFF
add mapped point rot/z_reg[7][8]/q rot_z_reg_reg[7][8]/QN  -type DFF DFF
add mapped point rot/z_reg[9][8]/q rot_z_reg_reg[9][8]/Q  -type DFF DFF
add mapped point rot/z_reg[9][8]/q rot_z_reg_reg[9][8]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
